"""initial migration

Revision ID: 3f755bcf4863
Revises: 
Create Date: 2026-10-03 16:31:23.026478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3f755bcf4863'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=True)
    op.create_table('methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methods_id'), 'methods', ['id'], unique=False)
    op.create_index(op.f('ix_methods_name'), 'methods', ['name'], unique=True)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('open_access', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_index(op.f('ix_papers_title'), 'papers', ['title'], unique=False)
    op.create_index(op.f('ix_papers_year'), 'papers', ['year'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('text_selection', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_id'), 'annotations', ['id'], unique=False)
    op.create_index(op.f('ix_annotations_paper_id'), 'annotations', ['paper_id'], unique=False)
    op.create_index(op.f('ix_annotations_user_id'), 'annotations', ['user_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_paper_id', sa.Integer(), nullable=False),
    sa.Column('target_paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['target_paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_paper_id', 'target_paper_id', name='uq_citation')
    )
    op.create_index(op.f('ix_citations_id'), 'citations', ['id'], unique=False)
    op.create_index(op.f('ix_citations_source_paper_id'), 'citations', ['source_paper_id'], unique=False)
    op.create_index(op.f('ix_citations_target_paper_id'), 'citations', ['target_paper_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('literature_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_literature_reviews_id'), 'literature_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_literature_reviews_user_id'), 'literature_reviews', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_paper_id'), 'notes', ['paper_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('paper_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'author_id', name='uq_paper_author')
    )
    op.create_index(op.f('ix_paper_authors_author_id'), 'paper_authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_paper_authors_id'), 'paper_authors', ['id'], unique=False)
    op.create_index(op.f('ix_paper_authors_paper_id'), 'paper_authors', ['paper_id'], unique=False)
    op.create_table('paper_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_chunks_id'), 'paper_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_paper_chunks_paper_id'), 'paper_chunks', ['paper_id'], unique=False)
    op.create_table('paper_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'dataset_id', name='uq_paper_dataset')
    )
    op.create_index(op.f('ix_paper_datasets_dataset_id'), 'paper_datasets', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_paper_datasets_id'), 'paper_datasets', ['id'], unique=False)
    op.create_index(op.f('ix_paper_datasets_paper_id'), 'paper_datasets', ['paper_id'], unique=False)
    op.create_table('paper_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'method_id', name='uq_paper_method')
    )
    op.create_index(op.f('ix_paper_methods_id'), 'paper_methods', ['id'], unique=False)
    op.create_index(op.f('ix_paper_methods_method_id'), 'paper_methods', ['method_id'], unique=False)
    op.create_index(op.f('ix_paper_methods_paper_id'), 'paper_methods', ['paper_id'], unique=False)
    op.create_table('research_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('preferred_domains', sa.JSON(), nullable=False),
    sa.Column('favorite_methods', sa.JSON(), nullable=False),
    sa.Column('topics_researching', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_profiles_id'), 'research_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_research_profiles_user_id'), 'research_profiles', ['user_id'], unique=True)
    op.create_table('research_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_id'), 'research_projects', ['id'], unique=False)
    op.create_index(op.f('ix_research_projects_user_id'), 'research_projects', ['user_id'], unique=False)
    op.create_table('saved_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'paper_id', name='uq_saved_paper')
    )
    op.create_index(op.f('ix_saved_papers_id'), 'saved_papers', ['id'], unique=False)
    op.create_index(op.f('ix_saved_papers_paper_id'), 'saved_papers', ['paper_id'], unique=False)
    op.create_index(op.f('ix_saved_papers_user_id'), 'saved_papers', ['user_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_id'), 'search_queries', ['id'], unique=False)
    op.create_index(op.f('ix_search_queries_user_id'), 'search_queries', ['user_id'], unique=False)
    op.create_table('collection_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'paper_id', name='uq_collection_paper')
    )
    op.create_index(op.f('ix_collection_papers_collection_id'), 'collection_papers', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_papers_id'), 'collection_papers', ['id'], unique=False)
    op.create_index(op.f('ix_collection_papers_paper_id'), 'collection_papers', ['paper_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['paper_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    op.create_table('research_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_conversations_id'), 'research_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_research_conversations_project_id'), 'research_conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_conversations_user_id'), 'research_conversations', ['user_id'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_id'), 'search_results', ['id'], unique=False)
    op.create_index(op.f('ix_search_results_paper_id'), 'search_results', ['paper_id'], unique=False)
    op.create_index(op.f('ix_search_results_search_id'), 'search_results', ['search_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['research_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_search_results_search_id'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_paper_id'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_research_conversations_user_id'), table_name='research_conversations')
    op.drop_index(op.f('ix_research_conversations_project_id'), table_name='research_conversations')
    op.drop_index(op.f('ix_research_conversations_id'), table_name='research_conversations')
    op.drop_table('research_conversations')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_collection_papers_paper_id'), table_name='collection_papers')
    op.drop_index(op.f('ix_collection_papers_id'), table_name='collection_papers')
    op.drop_index(op.f('ix_collection_papers_collection_id'), table_name='collection_papers')
    op.drop_table('collection_papers')
    op.drop_index(op.f('ix_search_queries_user_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_saved_papers_user_id'), table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_paper_id'), table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_id'), table_name='saved_papers')
    op.drop_table('saved_papers')
    op.drop_index(op.f('ix_research_projects_user_id'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_id'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index(op.f('ix_research_profiles_user_id'), table_name='research_profiles')
    op.drop_index(op.f('ix_research_profiles_id'), table_name='research_profiles')
    op.drop_table('research_profiles')
    op.drop_index(op.f('ix_paper_methods_paper_id'), table_name='paper_methods')
    op.drop_index(op.f('ix_paper_methods_method_id'), table_name='paper_methods')
    op.drop_index(op.f('ix_paper_methods_id'), table_name='paper_methods')
    op.drop_table('paper_methods')
    op.drop_index(op.f('ix_paper_datasets_paper_id'), table_name='paper_datasets')
    op.drop_index(op.f('ix_paper_datasets_id'), table_name='paper_datasets')
    op.drop_index(op.f('ix_paper_datasets_dataset_id'), table_name='paper_datasets')
    op.drop_table('paper_datasets')
    op.drop_index(op.f('ix_paper_chunks_paper_id'), table_name='paper_chunks')
    op.drop_index(op.f('ix_paper_chunks_id'), table_name='paper_chunks')
    op.drop_table('paper_chunks')
    op.drop_index(op.f('ix_paper_authors_paper_id'), table_name='paper_authors')
    op.drop_index(op.f('ix_paper_authors_id'), table_name='paper_authors')
    op.drop_index(op.f('ix_paper_authors_author_id'), table_name='paper_authors')
    op.drop_table('paper_authors')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_paper_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_literature_reviews_user_id'), table_name='literature_reviews')
    op.drop_index(op.f('ix_literature_reviews_id'), table_name='literature_reviews')
    op.drop_table('literature_reviews')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_citations_target_paper_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_source_paper_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_annotations_user_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_paper_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_papers_year'), table_name='papers')
    op.drop_index(op.f('ix_papers_title'), table_name='papers')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_methods_name'), table_name='methods')
    op.drop_index(op.f('ix_methods_id'), table_name='methods')
    op.drop_table('methods')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
