"""feat(db): add status, bookmarked, tags, saved_at to SavedPaper

Revision ID: f780aa2ba3f4
Revises: add_upload_and_lit_state
Create Date: 2026-10-03 19:20:12.376379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f780aa2ba3f4'
down_revision: Union[str, None] = 'add_upload_and_lit_state'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_papers', sa.Column('status', sa.String(), server_default='unread', nullable=False))
    op.add_column('saved_papers', sa.Column('bookmarked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('saved_papers', sa.Column('tags', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('saved_papers', sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_papers', 'saved_at')
    op.drop_column('saved_papers', 'tags')
    op.drop_column('saved_papers', 'bookmarked')
    op.drop_column('saved_papers', 'status')
    # ### end Alembic commands ###
